name: airport_auhtority_linkage_app
description: "Airport Flight and Billing System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  csv: ^6.0.0
  intl: ^0.19.0  # Downgraded for syncfusion_flutter_xlsio compatibility
  googleapis: ^11.0.0  # For gsheets
  googleapis_auth: ^1.6.0
  gsheets: ^0.5.0
  dropdown_button2: ^2.3.9
  url_launcher: ^6.3.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3
  firebase_database: ^11.1.4
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  file_picker: ^8.1.2
  mime: ^2.0.0
  path: ^1.9.0
  fl_chart: ^0.68.0
  pdf: ^3.11.0
  printing: ^5.13.2
  file_saver: ^0.2.14
  syncfusion_flutter_pdf: ^27.1.53
  universal_io: ^2.2.2
  path_provider: ^2.1.4
  open_file: ^3.5.9
  syncfusion_flutter_xlsio: ^27.1.53
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  cloud_functions: ^5.1.3
  firebase_core_web: ^2.17.5
  flutter_signin_button: ^2.0.0
  excel: ^4.0.6
  blur: ^4.0.2
  share_plus: ^10.0.3
  logger: ^2.0.0
  universal_html: ^2.0.8
  dio: ^5.7.0
  retry: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/images/airplane.webp
    - assets/credentials.json

  # Fonts configuration
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: NotoSansSymbols
      fonts:
        - asset: assets/fonts/NotoSansSymbols-Regular.ttf
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf      

# Optional: Add dependency overrides if needed for version conflicts
# dependency_overrides:
#   intl: ^0.19.0  # Example override if conflicts arise